### ISSUE TITLE
Contributions to main project

### ISSUE THREAD

**Issue by juanfranblanco** [panukettu/vscode-solidity#3]
Hi,

Any thoughts instead of creating a separate project, make contributions to the main extension? Somebody has just raised an issue, so feel free to add anything.

Juan

**Comment by panukettu** [comment]
> Hi,
> 
> Any thoughts instead of creating a separate project, make contributions to the main extension? Somebody has just raised an issue, so feel free to add anything.
> 
> Juan

Originally I just had to fix an issue with vscode-solidity crashing vscode in certain projects due to a definition lookup (since it was only extension with any support for eg. struct/using for lib patterns) 

Quickly realized the architecture required too much time to understand. Opted to brute forced a fix which trashed the extension performance with some expensive lookup, but the projects worked. Anyways I was also sure a better fix appears upstream. Well, that did not happen for some time so I had to start fixing my fix, branching out quickly from the original.

With this starting point it just never made sense to try sell it upstream as majority of users get 0 benefits and later quality of life improvements were already made into a codebase nothing like the original.

Anyways, as this project is almost "finished", I could recreate some features here into the main extension base and open a PR if people find them useful.

**Comment by panukettu** [comment]
Also "branching out from the original" does really mean it

<img width="823" alt="image" src="https://github.com/panukettu/vscode-solidity/assets/18403470/16657b8c-084d-4373-b245-d7227c08b16b">

**Comment by juanfranblanco** [comment]
Thanks, sorry I missed your response! Yes it will be cool if you see anything useful to push it there. I saw lots of formatting changes, after a quick browse, but interesting commands and probably fixes, although I just had a quick browse.
